#以下的内容很运行工具的关键，需要根据不同的APP定制
CRITICAL_ELEMENT:

  #Android
  #
  ANDROID_PACKAGE: xxx  #待执行的App包名，同Android App自动化测试配置一样
  ANDROID_MAIN_ACTIVITY: .splash.ui.SplashActivity    #启动的Activity，同Android App自动化测试配置一样
  #通过xpath指定要点击的元素的属性要求， 注意值两侧要加单引号''
  ANDROID_CLICK_XPATH_HEADER: ' ( string-length(@text)<30  or contains(@text,"允许") ) '
  #若App顶、底UI含有TabBar ,需指定TabBar的id, 多个id时用or拼接: 如'@resource-id="id1" or @resource-id="id2"',
  #  ANDROID_BOTTOM_TAB_BAR_ID: '@resource-id="com.sjst.xgfe.android.kmall:id/tab_txt"'
  #  ANDROID_BOTTOM_TAB_BAR_ID: '@text="首页"'
  ANDROID_BOTTOM_TAB_BAR_ID: '@text="购物车"'
  #  ANDROID_BOTTOM_TAB_BAR_ID: '@text="分类"'
  #  ANDROID_BOTTOM_TAB_BAR_ID: '@text="订单"'
  #  ANDROID_BOTTOM_TAB_BAR_ID: '@text="我的"'
  #底部的5个Tab Id都一样


  #iOS
  #若执行iOS App测试，必需指定以下IOS_开头的内容,
  #IOS_BUNDLE_ID: com.meituan.b2b.kmall.ep  #这是可切环境的包，#待执行的App包名，同Ios App自动化测试配置一样
  IOS_BUNDLE_ID: xxx  #灰度的包
  #手机桌面上显示的APP的名字（这个很重要，判断是否有Crash）
  #  IOS_BUNDLE_NAME: QA_368
  #  IOS_BUNDLE_NAME:  QA_444 #手机桌面上显示的APP的名字（这个很重要，判断是否有Crash）
  IOS_BUNDLE_NAME: xxx
  #IPA名字的前缀
  IOS_IPA_NAME: xxx    #ips文件名前缀   （这个很重要，判断是否有Crash）
  #  IOS_BOTTOM_TAB_BAR_TYPE: XCUIElementTypeTabBar
  IOS_BOTTOM_TAB_BAR_TYPE: XCUIElementTypeButton  #底部tab
  #  IOS_BOTTOM_TAB_BAR_TYPE: XCUIElementTypeStaticText     #文本,
  #  IOS_BOTTOM_TAB_BAR_TYPE: XCUIElementTypeImage #图片
  #  IOS_CLICK_XPATH_HEADER: '@visible="true" and string-length(@value)<30'
  IOS_CLICK_XPATH_HEADER: '@visible="true" and string-length(@value)<50'



  #微信小程序
  #微信小程序测试 使用参数 -y 时需指定小程序的名字
  WECHAT_MINI_PROGRAM_NAME: xxx

#****************************************************Monkey测试时根据需要更改下面的值，调节事件发生概率****************************************************
#每项为事件随机发生的次数，各项之和为100
MONKEY:
  #滑动
  SWIPE_RATIO: 5
  #点击
  CLICK_RATIO: 70
  #点击 MONKEY_SPECIAL_POINT_LIST 中的坐标 主要用于触发"返回"功能
  CLICK_SPECIAL_POINT_RATIO: 2
  #重启app
  RESTART_APP_RATIO: 0
  #长按
  LONG_PRESS_RATIO: 1
  #触发Home键 (Android Only)
  HOME_KEY_RATIO: 0
  #触发Back Key
  BACK_KEY_RATIO: 2
  #手势操作
  #双击
  DOUBLE_TAP_RATIO: 2
  #缩小(两指)
  PINCH_RATIO: 2
  #放大(两指)
  UNPINCH_RATIO: 2
  #拖拽
  DRAG_RATIO: 4
  #CLICK_ITEM_XPATH_LIST中指定元素的点击次数
  CLICK_ITEM_BY_XPATH_RATIO: 1


#（可选）Monkey操作相关的一些值
MONKEY_SPECIAL_ACTION:

  #设置需要点击的元素的xpath，点击次数由 CLICK_ITEM_BY_XPATH_RATIO 控制， 若找不到相应的元素则会忽略该事件
  CLICK_ITEM_XPATH_LIST:
  #- '//*[@resource-id="com.xes.jazhanghui.activity:id/tv_item_course"]'

  #提高测试效率，点击以下点(x,y)时会触发"后退"操作，避免在一个页面停留时间太久
  MONKEY_SPECIAL_POINT_LIST:
    - '80,160'

  #根据坐标长按某点10秒
  LONG_PRESS_LIST:
    - '100,250'

  #设置不点击的区域(圆形)， radius为圆半径， 坐标为不想点击区域的圆心
  MONKEY_BLACKLIST_POINT_LIST:
    - 'radius,10'
    - '0,0'


#****************************************************以下内容通常不需要修改****************************************************

#（可选）以下各值主要用于提高测试的效率，根据app着情修改或者不改
LIST:
  #UI元素中出现下列文字时 触发back键(iOS 由左向右划触发返回操作)
  PRESS_BACK_TEXT_LIST:
  #    - 返回

  #当App跳转到以下app时 触发back键，比如分享出去调的app
  PRESS_BACK_PACKAGE_LIST:
    #    - com.autonavi.minimap
    #    - com.android.settings
    #    - com.tencent.mm
    - com.android.camera   #系统相机，在app中容易调起系统相机
    - com.tencent.mm #商品分享到微信或者使用微信支付
    - com.tencent.mobileqq #商品分享到qq
    - com.eg.android.AlipayGphone #商品使用支付宝支付

  #当前遇到以下Activity时 触发back键 (Android only)
  PRESS_BACK_ACTIVITY_LIST:
    - .mvp.servicecenter.view.ServiceCenterMapDetailActivity
    - activity.SobotChatActivity
    - com.android.internal.app.ResolverActivity

  #待输入文本的控制类型,把这里补充下
  INPUT_CLASS_LIST:
    - android.widget.TextView
    - XCUIElementTypeTextField
    - XCUIElementTypeSecureTextField

  #待输入的文本（随机选中后选列表中的一个）
  INPUT_TEXT_LIST:
    - '123'
    - 'ABC'

  #除了APP本身的包名外 根据以下包名判断是否跳出了待测APP,当app跳转到以下app时被认为是合法，会继续遍历操作，否则，就当做是Crash
  ANDROID_VALID_PACKAGE_LIST:
    #  - com.miui.securitycenter
    #  - com.android.server.telecom
    #  - com.lbe.security.miui
    #  - gallery
    #  - packageinstaller
    - com.android.camera   #系统相机，在app中容易调起系统相机
    - com.tencent.mm #商品分享到微信或者使用微信支付
    - com.tencent.mobileqq #商品分享到qq
    - com.eg.android.AlipayGphone #商品使用支付宝支付

  #同ANDROID_VALID_PACKAGE_LIST
  IOS_VALID_BUNDLE_LIST:
    - 照片
    - 微信

  #白名单，遇到包含以下文本的控件，会多次点击（默认所有控件只点一次）
  ITEM_WHITE_LIST:
    - 确定
    - 允许
    - 退出
    - 取消
    - 已解决
    - 提交

  #不点击包含以下文本的控件
  ITEM_BLACKLIST:
    #    - 客服
    #    - 电话
    #    - 不允许
    #    - 拒绝
    #    - 拍照
    #    - 禁止
    #    - 呼叫
    #    - 低电量模式
    #    - 关闭
    #    - 打车
    - Debug 面板
    - 返回“Safari 浏览器”
  #    - vConsole
  #    - '//*[@text="去付款"]'

  #不点击以下类型控件及其子元素
  IOS_EXCLUDE_BAR:
    #手机顶部状态栏
    - XCUIElementTypeStatusBar
  #    #键盘
  #    - XCUIElementTypeKeyboard

  #不点击以下类型的元素
  IOS_EXCLUDE_TYPE:
    - XCUIElementTypeButton
  #    - XCUIElementTypeOther
  #    - XCUIElementTypeKey
  #    - XCUIElementTypeWindow
  #    - XCUIElementTypeApplication

  #不点击以下类型的元素
  ANDROID_EXCLUDE_TYPE:
    - android.widget.FrameLayout
    - android.widget.ImageButton

  #解释待续
  NODE_NAME_EXCLUDE_LIST:
    - selected
    - instance
    - checked
    - naf
    - content

  #解释待续
  STRUCTURE_NODE_NAME_EXCLUDE_LIST:
    #iOS
    - name

    #Android
    - text


#****************************************************以下内容通常不需要修改****************************************************

#微信的配置 在运行小程序测试时会用到
WECHAT_CONFIG:
  #Android 配置
  WECHAT_ANDROID_PACKAGE: com.tencent.mm
  WECHAT_ANDROID_MAIN_ACTIVITY: com.tencent.mm.ui.LauncherUI

  #iOS  配置
  WECHAT_IOS_BUNDLE_ID: com.tencent.xin
  WECHAT_IOS_BUNDLE_NAME: 微信
  WECHAT_IOS_IPA_NAME: wechat

#一些全局的配置
GENERAL:
  #截屏数量
  #  SCREENSHOT_COUNT: 5000
  SCREENSHOT_COUNT: 5000
  #Crash时截图显示步骤数量
  CRASH_PIC_COUNT: 10
  #遍历深度
  MAX_DEPTH: 1000
  #点击次数
  MAX_CLICK_COUNT: 1000000
  #查找元素的时间
  DEFAULT_WAIT_SEC: 0
  #  DEFAULT_WAIT_SEC: 1
  #查找元素的间隔时间
  #  DEFAULT_POLLING_INTERVAL_SEC: 0
  DEFAULT_POLLING_INTERVAL_SEC: 1
  #是否忽略Crash,设为true时,crash后会重启app然后继续遍历
  IGNORE_CRASH: false
  #遍历的过程中进行向上划动操作  ！！！此项会加长遍历时间！！！
  #  ENABLE_VERTICAL_SWIPE: false
  ENABLE_VERTICAL_SWIPE: true
  #遍历运行时间限制(分钟)，CRAWLER_RUNNING_TIME的起终点都在xPathUtil文件中
  #  CRAWLER_RUNNING_TIME: 60
  CRAWLER_RUNNING_TIME: 5
  #  CRAWLER_RUNNING_TIME: 300
  #控制是否生成视频
  GENERATE_VIDEO: false
  #控制视频方向，竖屏或模屏
  VIDEO_VERTICAL: false
  #每个UI变化X次时，检测是否需要自动登录
  USER_LOGIN_INTERVVAL: 300
  #忽略底部元素Bounds值
  REMOVE_BOTTOM_BOUND: true

#一些默认值
DEFAULT_VALUE:
  #0.0.0.0代表Appium Server运行在本地
  APPIUM_SERVER_IP: 0.0.0.0
  #Appium端口
  PORT: 4723
  #IOS WDA_PORT
  IOS_WDA_PORT: 8100


#输出更多的log 主要用于调试工具用
LOG:
  #将性能数据写入数据库相关的log
  DB_LOG: false
  #性能数据相关log
  PERF_LOG: false
  #是否开启DOM树在log中的显示
  DOM_DISPLAY: false


#时序数据库 用于记录性能数据 与-e 一起使用
INFLUXDB:
  DB_PORT: 8086
  DB_IP: localhost

#*******************ENABLE_AUTO_LOGIN 为true里需要修改以下内容**************************
#（可选）自动登录时查找控件所需要的信息,当找到列表中第一个元素时会按顺序操作以下元素。注意xpath中的属性值要加双引号""
#如果不需要自动登录功能以下值不需要修改
LOGIN_ELEMENTS:
  #开启自动登录功能
  ENABLE_AUTO_LOGIN: false

  #Android 登录相关元素及操作
  LOGIN_ELEMENTS_ANDROID:
    - ANDROID_Allow1:
        XPATH: '//*[@text="允许"]'
        ACTION: click
        VALUE: '1'
    - ANDROID_Allow2:
        XPATH: '//*[@text="允许"]'
        ACTION: click
        VALUE: '1'
    - ANDROID_Allow3:
        XPATH: '//*[@text="允许"]'
        ACTION: click
        VALUE: '1'
    - ANDROID_AlwaysAllow1:
        XPATH: '//*[@text="总是允许"]'
        ACTION: click
        VALUE: '1'
    - ANDROID_AlwaysAllow2:
        XPATH: '//*[@text="总是允许"]'
        ACTION: click
        VALUE: '1'
    - ANDROID_AlwaysAllow3:
        XPATH: '//*[@text="总是允许"]'
        ACTION: click
        VALUE: '1'
    - ANDROID_PrivacyPopup:
        XPATH: '//*[@text="同意"]'
        ACTION: click
        VALUE: '1'
    #    - ANDROID_StageVirtual:
    #        XPATH: '//*[@text="Stage 虚拟"]'
    #        ACTION: click
    #        VALUE: '2'
    #    - ANDROID_PackageName:
    #        XPATH: '//*[@text="DEV"]'
    #        ACTION: click
    #        VALUE: '2'
    #    - ANDROID_PrivacyPopup1:
    #        XPATH: '//*[@text="同意"]'
    #        ACTION: click
    #        VALUE: '1'
    - ANDROID_StageVirtual1:
        XPATH: '//*[@text="Stage 虚拟"]'
        ACTION: click
        VALUE: '3'
    - ANDROID_StageVirtual:
        XPATH: '//*[@text="跳过"]'
        ACTION: click
        VALUE: '2'
    - ANDROID_GoLogin:
        XPATH: '//*[@text="去登录"]'
        ACTION: click
        VALUE: '2'
    - ANDROID_Windows_Popup0:
        XPATH: '//*[@resource-id="com.sjst.xgfe.android.kmall:id/ivClose"]'
        ACTION: click
        VALUE: '2'
    - ANDROID_Me:
        XPATH: '//*[@text="我的"]'
        ACTION: click
        VALUE: '1'
    - ANDROID_PleaseLogin:
        XPATH: '//*[@text="请登录/注册"]'
        ACTION: click
        VALUE: '1'
    - ANDROID_AccountPasswordLogin:
        XPATH: '//*[@text="账号密码登录"]'
        ACTION: click
        VALUE: '1'
    - ANDROID_USERNAME:
        XPATH: '//*[@text="请输入账号"]'
        ACTION: input
        VALUE: '13031190943'
    - ANDROID_PASSWORD:
        XPATH: '//*[@resource-id="com.sjst.xgfe.android.kmall:id/password"]'
        ACTION: input
        VALUE: 'Ceshi123'
    - ANDROID_LOGIN_BUTTON:
        XPATH: '//*[@text="登录"]'
        ACTION: click
        VALUE: '2'
    - ANDROID_LOGIN_BUTTON_ID:
        XPATH: '//*[@resource-id="com.sjst.xgfe.android.kmall:id/account_controller_btn"]'
        ACTION: click
        VALUE: '2'
    - ANDROID_Ikonw:
        XPATH: '//*[@text="我知道了"]'
        ACTION: click
        VALUE: '2'
    - ANDROID_Windows_Popup:
        XPATH: '//*[@resource-id="com.sjst.xgfe.android.kmall:id/ivClose"]'
        ACTION: click
        VALUE: '2'


  #iOS登录相关元素及操作
  LOGIN_ELEMENTS_IOS:
    - IOS_AGREE:
        XPATH: '//*[@value="同意"]'
        ACTION: click
        VALUE: '1'
    - IOS_GoLogin:
        XPATH: '//*[@value="去登录"]'
        ACTION: click
        VALUE: '2'
    - IOS_Me:
        XPATH: '//*[@name="我的"]'
        ACTION: click
        VALUE: '1'
    - IOS_PleaseLogin:
        XPATH: '//*[@value="请登录/注册"]'
        ACTION: click
        VALUE: '1'
    - IOS_AccountPasswordLogin:
        XPATH: '//*[@value="账号密码登录"]'
        ACTION: click
        VALUE: '1'
    - IOS_USERNAME:
        XPATH: '//*[@value="请输入账号"]'
        ACTION: input
        VALUE: '13031190943'
    - IOS_PASSWORD:
        XPATH: '//*[@value="请输入密码"]'
        ACTION: input
        VALUE: 'Ceshi123'
    - IOS_LOGIN_BUTTON:
        XPATH: '//*[@label="登录"]'
        ACTION: click
        VALUE: '2'
    - IOS_LOGIN_BUTTON1:
        XPATH: '//*[@name="MTSignInVC_Button_Login"]'
        ACTION: click
        VALUE: '2'
#    - IOS_Go:
#        XPATH: '//*[@name="Go"]'
#        ACTION: click
#        VALUE: '2'
#    - DRAG:
#        XPATH: '//*[@resource-id="com.xes.jazhanghui.activity:id/xes_login_username"]'
#        ACTION: drag
#        VALUE: '250,1050,800,1050,800,1550'